version: '3.9'
services:
  pgvector:
    image: ankane/pgvector:latest
    container_name: trainflow-pgvector
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knowledge
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

