name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node-build:
    name: Node build and health check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: TypeScript build
        run: npm run build

      - name: Start server and verify /health
        run: |
          node dist/server.js &
          SERVER_PID=$!
          sleep 2
          curl -sS http://localhost:4000/health
          kill $SERVER_PID || true

  python-backtesting:
    name: Backtesting.py env check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backtesting_py
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Import smoke tests
        run: |
          python - << 'PY'
          import fastapi, uvicorn
          import numpy, pandas
          import backtesting
          print('imports-ok')
          PY

  docker-build:
    name: Build Docker image for Backtesting.py
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t trainflow-backtest:ci ./backtesting_py

